package com.atm.simulation.view;

import com.atm.simulation.entity.Account;
import com.atm.simulation.service.AccountService;
import com.atm.simulation.service.TransactionService;
import com.atm.simulation.util.InputUtil;
import com.atm.simulation.util.ValidationUtil;

import java.util.Random;

public class TransferView {

    private WelcomeView welcomeView;
    private TransactionView transactionView;
    private AccountService accountService;
    private TransactionService transactionService;

    public TransferView(AccountService accountService){
        this.accountService = accountService;
    }

    public void fundScreen(Integer accNumb) {
        //step 1
        System.out.println("Please enter destination account and \n" +
                "press enter to continue or");

        //to get key value using key listener
        ValidationUtil.listener(accNumb);
        var input = InputUtil.inputString("press cancel (Esc) to go back to Transaction: ");
        String value = ValidationUtil.getValue();
        if(value.equalsIgnoreCase("esc")){
            ValidationUtil.setValue("");
            transactionView.transactionScreen(accNumb);
        }else{
            input = value;
            System.out.println(value);
            ValidationUtil.setValue("");
        }

        //step 2 amount
        System.out.println("Please enter transfer amount and press enter to continue or ");
        var amount = InputUtil.inputString("press enter to go back to Transaction:");
        if (amount.isBlank() || amount.isEmpty()) {
            transactionView.transactionScreen(accNumb);
        }

        //step 3 refNo
        System.out.println("Reference Number: (This is an autogenerated random 6 digits number)");
        var input3 = InputUtil.inputString("Press enter to continue or click 'x' Enter to go back to Transaction: ");

        if (input3.equalsIgnoreCase("x")) {
            transactionView.transactionScreen(accNumb);
        } else if (!input3.isEmpty() || !input3.isBlank()) {
            System.out.println("Invalid Reference Number");
            fundScreen(accNumb);
        }

        Random random = new Random();
        int randomNumber = random.nextInt(900000) + 100000;

        System.out.println("Transfer Confirmation\n" +
                "Destination Account : " + input.replace("\n","") + "\n" +
                "Transfer Amount     : $" + amount + "\n" +
                "Reference Number    : " + randomNumber + "\n" +
                "\n" +
                "1. Confirm Trx\n" +
                "2. Cancel Trx");

        var input4 = InputUtil.inputString("Choose option[2]:");

        if (input4.equals("1")) {
            //validate step 1
            try {
                transactionService.fundTransaction(accNumb,input,amount,randomNumber);
            }catch (Exception e){
                System.out.println(e.getMessage()
                );
                fundScreen(accNumb);
            }
            fundSummaryScreen(Integer.parseInt(amount), randomNumber,Integer.parseInt(input), accNumb);
        } else if (input4.equals("2")) {
            fundScreen(accNumb);
        }

    }

    public void fundSummaryScreen(Integer trfAmount, Integer refNum, Integer accDest, Integer accNumb){
        Account account = accountService.getAccount(accNumb);
        System.out.println("Fund Transfer Summary\n" +
                "Destination Account : " + accDest + "\n" +
                "Transfer Amount     : $" + trfAmount + "\n" +
                "Reference Number    : " + refNum + "\n" +
                "Balance             : $" + account.getBalance().getBalance() + "\n" +
                "\n" +
                "1. Transaction\n" +
                "2. Exit");
        var input = InputUtil.inputString("Choose option[2]");
        if (input.equals("1")) {
            transactionView.transactionScreen(accNumb);
        } else if (input.equals("2")) {
            welcomeView.welcomeScreen();
        }
    }

    public void setParentView(TransactionView transactionView, WelcomeView welcomeView, TransactionService transactionService) {
        this.transactionView = transactionView;
        this.welcomeView = welcomeView;
        this.transactionService = transactionService;
    }
}
